package 异常;

public class FinallyTest1 {

	public static void main(String[] args) {
		try //将可能会发生异常的代码用try包起来
		{
			int[] nums = {3,5,9};
			System.out.println(nums[9]);//超出数组范围
		}
		catch(ArrayIndexOutOfBoundsException e)
		{
			System.out.println("数组超出范围");
		}
		finally
		{
			System.out.println("我是finally"); //无论程序是否有异常，finally中的代码都会执行
		}
	}

}
