package 异常;

public class ExceptionTest1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Integer i1 = 1;
		try //将可能会发生异常的代码用try包起来
		{
			System.out.println("aaa");
			int i2 = i1;
			System.out.println("bbb"); //当发现int i2 = i1这行代码发现异常的时候，那么try块里面的下面的代码就不会执行了，但是try块外面的代码还是会执行
		}
		catch(NullPointerException e) //catch抓住异常, NullPointerException为要抓住（catch）的异常的类型, e为这个异常对象
		{
			//当发生被抓住的异常,(比如NullPointerException) 那么就会执行catch中的代码
			System.out.println("i1不能为null");
		}
		System.out.println("ccc");
	}

}
