package 异常;

public class ExceptionTest1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Integer i1 = null;
		try //将可能会发生异常的代码用try包起来
		{
			int i2 = i1;
		}
		catch(NullPointerException e) //catch抓住异常, NullPointerException为要抓住（catch）的异常的类型, e为这个异常对象
		{
			System.out.println("i不能为null");
		}
	}

}
